version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: vendor-machine-elastic
    ports: ['9200:9200']
    environment:
      - "ELASTIC_PASSWORD=elastic"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
      - "TAKE_FILE_OWNERSHIP=1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - '../var/elasticsearch:/usr/share/elasticsearch/data'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: vendor-machine-kibana
    environment:
      - "ELASTICSEARCH_HOSTS: http://elasticsearch:9200"
      - "ELASTIC_PASSWORD=elastic"
    links:
      - elasticsearch
    ports: ['5601:5601']
    depends_on:
      - elasticsearch

networks:
  default:
    external:
      name: vendingmachine