# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

    file_coin_box: '%kernel.project_dir%/var/store/coinBox.json'
    file_coin_user: '%kernel.project_dir%/var/store/coinUser.json'

    imports: [0.5, 0.10, 0.25, 1.00]

    products:
        -
            name: 'WATER'
            price: 0.65
        -
            name: 'JUICE'
            price: 1.00
        -
            name: 'SODA'
            price: 1.50

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Shared\Domain\Bus\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\Shared\Domain\Bus\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/UI/Controller/'
        tags: ['controller.service_arguments']

    App\Domain\Coin\CoinBoxRepository:
        class: App\Infrastructure\Persistence\FileSystem\FileSystemCoinBoxRepository

    App\Domain\Coin\CoinUserRepository:
        class: App\Infrastructure\Persistence\FileSystem\FileSystemCoinUserRepository

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
